Standardize sorting for table & export functions
yeatmanlab/roar-dashboard pull request #207
Opened 2023-12-01 22:43 UTC by kellyel

For the letter subscore table, I used `_toUpper` to sort the table, but `_toLower` to sort the data on export. This PR standardizes those operations

2023-12-01 23:18 UTC, ksmontville approved these changes
Using PR link, I was able to export the whole table for the letter subscores without issue.

2023-12-04 18:55 UTC, richford requested changes

2023-12-04 18:55 UTC, richford commented on src/components/reports/SubscoreTable.vue
> +      { field: "scores.pa.skills", header: "Skills To work on", dataType: "text"}
```suggestion
      { field: "scores.pa.skills", header: "Skills To Work On", dataType: "text"}
```

2023-12-04 18:56 UTC, richford approved these changes

2023-12-05 17:46 UTC, merged