funtion in the HomeParticipant component to delete tag for CSS issues
yeatmanlab/roar-dashboard pull request #218
Opened 2023-12-08 17:24 UTC by Emily-ejag

This PR has a function in the HomParticipant.vue component to delete the style tag that is left behind for the injection of the games, it looks for the .this-is-roar tag that must be added to all the games' CSSs

2023-12-08 17:53 UTC, richford requested changes
Looks good! Could I ask you to run
```
npm run format
```
and then push those changes as well.

2023-12-08 18:46 UTC, Emily-ejag commented
Ok done and pushed

2023-12-08 19:30 UTC, ksmontville approved these changes

2023-12-11 21:17 UTC, Emily-ejag commented
Hi, let me know if everything is correct :)

2023-12-12 12:58 UTC, richford approved these changes

2023-12-12 12:58 UTC, merged