reduce penalization
yeatmanlab/roar-dashboard pull request #244
Opened 2023-12-18 20:11 UTC by Emily-ejag

Going back to having merge issues

2023-12-28 13:01 UTC, richford requested changes

2023-12-28 13:01 UTC, richford commented on src/pages/ScoreReport.vue
> +          <label for="ms-columns" class="view-label">View</label>
Passing in the class `view-label` works with the slot, but then the label is formatted differently than all of the other drop-down labels. Can we find a way to standardize all of the multi-select labels?

2023-12-28 13:18 UTC, richford commented
@Emily-ejag, I just submitted a bunch of comments and suggestions in my review but neglected to write my overall review comments so I'll do it here:

- Overall, it looks really good. I like the new design.
- A lot of my comments have to do with using css variables instead of hard-coding colors in each css file. I'd prefer to use css variables so that it's easy to change them all in one place. This makes it easier to maintain and also easier to experiment with different colors during development.
- The other uses of RoarDataTable are now broken. For example, check out the "List Organizations" page at the /list-orgs route.
- I don't yet understand that cause, but when I checkout this branch, the behavior on my localhost is different than the behavior on the PR preview site. Namely it works on localhost but not on the staging site. Also, the login icons for google and clever are much bigger on the staging site. We'll have to resolve this before merging. I can co-work with you on that. But it would be helpful to resolve the other above issues first.

2023-12-28 16:16 UTC, Emily-ejag commented on src/components/AdministratorSidebar.vue
> +</style> -->
Done

2023-12-28 16:26 UTC, Emily-ejag commented on src/assets/styles/components/button.scss
> +  border: 1px solid #7F2D48;
done

2023-12-28 16:26 UTC, Emily-ejag commented on src/assets/styles/components/button.scss
> +  background: #7F2D48;
done

2023-12-28 16:26 UTC, Emily-ejag commented on src/assets/styles/components/input-switch.scss
> +  background: #7F2D48;
done

2023-12-28 16:26 UTC, Emily-ejag commented on src/assets/styles/components/input-switch.scss
> +  background: #7F2D48;
done

2023-12-28 16:27 UTC, Emily-ejag commented on src/pages/ScoreReport.vue
> +// import { getSidebarActions } from '@/router/sidebarActions';
done

2023-12-28 16:29 UTC, Emily-ejag commented on src/pages/ScoreReport.vue
> +    <!-- </aside> -->
done

2023-12-28 16:30 UTC, Emily-ejag commented on src/pages/ScoreReport.vue
> +      <!-- :header="`Administration Score Report: ${administrationInfo?.name ?? ''}`" -->
done

2023-12-28 16:33 UTC, Emily-ejag commented on src/pages/ScoreReport.vue
> +            <span :class="spinIcon"> Refresh</span>
done

2024-01-08 20:53 UTC, closed without merging

2024-01-08 20:54 UTC, Emily-ejag commented
The link was not longer available