CSS Dashboard Update 5
yeatmanlab/roar-dashboard pull request #282
Opened 2024-01-12 22:56 UTC by Emily-ejag

preview

2024-01-18 19:38 UTC, kellyel requested changes
It's looking good so far. I left some suggestions. Could I ask you to remove all the commented code throughout the PR if we're not using it? 

I also had a look at the PR link. There are a few things I feel should be resolved (or at least let me know the thinking behind, I might be out of the loop on these decisions!)
1. There's a panel header on the admin home page, but not on the individual document pages. Is this intended?
<img width="1423" alt="CSS Review 1" src="https://github.com/yeatmanlab/roar-dashboard/assets/127352507/0e59529e-8160-4652-ac68-3b82ff6ecea7">

3. If we're getting rid of panel headers on the page, could we remove the vertical lines that come from below them? (The ones that wrap around the whole form). If not, could we have those match in color?
4. If the panel headers should be present, could we give the header text a bit of padding? Right now that text is top-left aligned. 
5. In the header, the dropdown for sorting should also get a bit of vertical padding.
6. The menu button is present for participant users. That should disappear for non-admins.
7. Also on participant, it seems the 'select assignment' dropdown is in the wrong place.
<img width="532" alt="CSS Review 2" src="https://github.com/yeatmanlab/roar-dashboard/assets/127352507/31956325-4207-4663-bf90-6b933a01afbe">

9. Are there two primary colors? On the login page, the background red is very deep whereas the red on all other pages are the new lighter color.
10. On the dropdown navigation menu, could we possibly vertical center each of the items? When you hover over them they're all top-aligned. This also leads to a few of the icons looking not in-line with the text that follows it.

Also this is not the right venue for a styling discussion, however the overlapping shadows on the tabs look a bit weird to me. I understand we are trying to make them look clickable, however is there a way to make the tabs not overlap each other?
<img width="1054" alt="CSS Review 3" src="https://github.com/yeatmanlab/roar-dashboard/assets/127352507/157e85d3-6876-48cb-ab4c-74f407aec911">

2024-01-18 19:38 UTC, kellyel commented on src/components/CardAdministration.vue
> +// });
If this computed function is no longer needed, we can delete
```suggestion

```

2024-01-18 22:44 UTC, Emily-ejag commented
I believe all the changes are done

2024-01-18 23:07 UTC, richford commented on src/components/CreateAdministration.vue
> +
Same here.

2024-01-18 23:07 UTC, richford commented on src/components/CreateAdministrator.vue
> +// import { fetchDocById } from '@/helpers/query/utils';
Same comment here about preferring deletion over commenting.

2024-01-18 23:08 UTC, richford commented on src/components/CreateOrgs.vue
> +// const sidebarActions = ref(getSidebarActions(isSuperAdmin.value, true));
Same comment here about preferring deletion over commenting.

2024-01-18 23:08 UTC, richford commented on src/components/ListOrgs.vue
> +            <p class="text-center">Still Loading Organization data</p>
```suggestion
            <p class="text-center">Loading organization data</p> 
```

2024-01-18 23:08 UTC, richford commented on src/components/ListOrgs.vue
> +// const sidebarActions = ref(getSidebarActions(isSuperAdmin.value, true));
Same comment here about preferring deletion over commenting.

2024-01-18 23:09 UTC, richford commented on src/components/ListOrgs.vue
> +  console.log("I am loading the name, abbreviation, address and tags")
```suggestion
```

2024-01-18 23:09 UTC, richford commented on src/components/ListOrgs.vue
> +    console.log("I am loading the districts and schools")
```suggestion
```

2024-01-18 23:09 UTC, richford commented on src/components/ListOrgs.vue
> +    console.log("I am loading the districts, schools and classess")
```suggestion
```

2024-01-18 23:09 UTC, richford commented on src/components/ListUsers.vue
> +// import { fetchDocById } from '../helpers/query/utils';
Same comment here about preferring deletion over commenting.

2024-01-18 23:10 UTC, richford commented on src/components/NavBar.vue
> +import { ref,computed } from 'vue';
```suggestion
import { ref, computed } from 'vue';
```

2024-01-18 23:10 UTC, richford commented on src/components/NavBar.vue
> + import { useQuery } from '@tanstack/vue-query';
```suggestion
 import { getSidebarActions } from '@/router/sidebarActions'
 import { fetchDocById } from '@/helpers/query/utils';
 import { useQuery } from '@tanstack/vue-query';
```

2024-01-18 23:10 UTC, richford commented on src/components/NavBar.vue
> +// ]
```suggestion
```

2024-01-18 23:10 UTC, richford commented on src/components/NavBar.vue
> +// const sidebarActions = ref(getSidebarActions(authStore.isUserSuperAdmin, !isAtHome.value));
```suggestion
```

2024-01-18 23:11 UTC, richford commented on src/components/RoarDataTable.vue
> +      <PvColumn selection-mode="multiple" header-style="width:3rem; " :reorderable-column="false" frozen />
```suggestion
      <PvColumn selection-mode="multiple" header-style="width: 3rem;" :reorderable-column="false" frozen />
```

2024-01-18 23:11 UTC, richford commented on src/components/RoarDataTable.vue
> +              :style="`background-color: ${_get(colData, col.tagColor)}; min-width: 2rem; color:white; ${
```suggestion
              :style="`background-color: ${_get(colData, col.tagColor)}; min-width: 2rem; color: white; ${
```

2024-01-18 23:12 UTC, richford commented on src/components/RoarDataTable.vue
> +// import _debounce from 'lodash/debounce';
```suggestion
```

2024-01-18 23:12 UTC, richford commented on src/components/RoarDataTable.vue
> +// import PvInputSwitch from 'primevue/inputswitch';
```suggestion
```

2024-01-18 23:13 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +              <div class="taskURLs">
I'd like to use kebab case for css classes.

```suggestion
              <div class="task-urls">
```

2024-01-18 23:13 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +              <div class="taskURLs">
Same here
```suggestion
              <div class="task-urls">
```

2024-01-18 23:13 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +          <div class="addField">
Same here
```suggestion
          <div class="add-field">
```

2024-01-18 23:14 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +.addField, .form-submit  {
```suggestion
.add-field, .form-submit  {
```

2024-01-18 23:14 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +.p-dropdown, .taskURLs {
```suggestion
.p-dropdown, .task-urls {
```

2024-01-18 23:14 UTC, richford commented on src/components/tasks/RegisterTask.vue
> +          <div class="addField">
```suggestion
          <div class="add-field">
```

2024-01-18 23:14 UTC, richford commented on src/pages/AdministrationProgress.vue
> +// import { getSidebarActions } from '@/router/sidebarActions';
Same comment here about preferring deletion over commenting.

2024-01-18 23:14 UTC, richford commented on src/pages/AdministrationProgress.vue
> +// const sidebarActions = ref(getSidebarActions(authStore.isUserSuperAdmin, true));
Same comment here about preferring deletion over commenting.

2024-01-18 23:15 UTC, richford commented on src/pages/HomeAdministrator.vue
> +// import { getSidebarActions } from '../router/sidebarActions';
Same comment here about preferring deletion over commenting.

2024-01-18 23:15 UTC, richford commented on src/pages/HomeAdministrator.vue
> +// import AdministratorSidebar from '@/components/AdministratorSidebar.vue';
Same comment here about preferring deletion over commenting.

2024-01-18 23:15 UTC, richford commented on src/pages/HomeAdministrator.vue
> +// });
Same comment here about preferring deletion over commenting.

2024-01-18 23:16 UTC, richford commented on src/pages/RegisterStudents.vue
> +// import { getSidebarActions } from '../router/sidebarActions';
Same comment here about preferring deletion over commenting.

2024-01-18 23:16 UTC, richford commented on src/pages/RegisterStudents.vue
> +// const sidebarActions = ref(getSidebarActions(authStore.isUserSuperAdmin, true));
Same comment here about preferring deletion over commenting.

2024-01-18 23:17 UTC, richford commented on src/pages/ScoreReport.vue
> +
Same comment here about preferring deletion over commenting.

2024-01-18 23:23 UTC, richford commented on src/pages/ScoreReport.vue
> +            id="view-columns"
Shouldn't this `id` be an `input-id` and should it match the `for` param of the `label` element?
```suggestion
          <label for="view-columns" class="view-label">View</label>
          <PvDropdown
            input-id="view-columns"
```

2024-01-18 23:56 UTC, Emily-ejag commented on src/components/tasks/RegisterTask.vue
> +              <div class="taskURLs">
done

2024-01-18 23:58 UTC, Emily-ejag commented on src/components/tasks/RegisterTask.vue
> +          <div class="addField">
done

2024-01-19 00:16 UTC, richford commented
Hi @Emily-ejag,

I've been thinking about this PR and have decided that it would be best to break it up into multiple PRs. There are some of the style changes that I'm not quite ready to sign off on yet. I'd still like to workshop some things. But then there are other improvements that are ready to go (e.g., moving the menu bar, adding a compact table view). I think it would be easier to merge multiple small PRs with logically distinct changes.

I really appreciate all of the hard work you've done on this PR. And I know it's frustrating to have me come back after multiple reviews and merge conflicts only to ask you to resubmit as multiple smaller PRs, but I think it'll be worth the effort. Can you close this without merging and then resubmit multiple PRs as follows:
1. Moving the menu button to the nav bar (using `PvMenu` instead of `Menu` to maintain consistency with the rest of the site
2. Adding compact table views
3. Modifying panels and headers
4. Changing colors
5. Anything else that I missed.

2024-01-19 00:16 UTC, richford commented
If it helps, you can use `git cherry-pick` to easily break up this branch into multiple smaller branches.

2024-01-25 23:35 UTC, closed without merging