Filter on user fields
yeatmanlab/roar-dashboard pull request #311
Opened 2024-01-26 00:08 UTC by kellyel

This PR allows users to filter on fields other than scores in the score report, as well as sorting.

2024-01-26 12:42 UTC, richford requested changes
This looks great @kellyel! Thanks for all of your hard work. I have two minor requests and one major one.

- Sorting by grade results in no data table to be displayed.
- I made two suggestions for removing commented out code.

2024-01-26 12:42 UTC, richford commented on src/helpers/query/assignments.js
> +      // }))
```suggestion
```

2024-01-26 12:42 UTC, richford commented on src/helpers/query/assignments.js
> +    //   });
```suggestion
```

2024-01-27 23:37 UTC, kellyel commented
Feedback addressed:
- Change wording of filters in dropdown
- Allow filters to be applied to scores from any view (color, percentile, standard, raw)
- Prevent user from filtering on blacklisted columns (letter)
- Visually remove option to filter on blacklisted columns. I am as of right now unable to remove the button itself, however I have disabled sorting on that column (no action happens), and I was able to remove the icon for those columns. the only indication that there is a button there is the hover event. I am not 100% happy with this, and will return to the problem later.

2024-01-30 17:22 UTC, richford approved these changes

2024-01-30 17:22 UTC, merged