WIP: view reliability
yeatmanlab/roar-dashboard pull request #355
Opened 2024-02-06 02:21 UTC by Emily-ejag

Able to grab reliability and color not reliable to gray

2024-02-06 17:36 UTC, richford commented
Task linked: [CU-868737x60 Visually encode run reliability in score reports](https://app.clickup.com/t/868737x60)

2024-02-06 23:49 UTC, richford requested changes
Thanks @Emily-ejag. I left some in-line comments with suggestions for improvements. But a larger issue is that this breaks filtering on scores.

2024-02-06 23:49 UTC, richford commented on src/components/RoarDataTable.vue
> +    }
I'd suggest here:
- Saving the flags to a variable for readability
- Converting the camel cased flags to lower case and separating by commas and spaces

```suggestion
    const flags = colData.assignment.assessments[index].engagementFlags;
    if(flags !== undefined && flags !== '' && !colData.assignment.assessments[index].reliable){
      toolTip += '\n' + 'Reliability: ' + Object.keys(flags).map(_lowerCase).join(', ') + '\n';
    }
```

This suggestion uses [lodash's `lowerCase` method](https://lodash.com/docs/4.17.15#lowerCase), so you'll have to import that above as well.

2024-02-06 23:49 UTC, richford commented on src/components/RoarDataTable.vue
> +    }
See above suggestion for PA.

2024-02-06 23:49 UTC, richford commented on src/components/RoarDataTable.vue
> +    }
See above suggestion for PA

2024-02-06 23:49 UTC, richford commented on src/components/RoarDataTable.vue
> +    }
See above suggestion for PA

2024-02-06 23:49 UTC, richford commented on src/components/RoarDataTable.vue
> +    }
See above suggestion for PA.

2024-02-06 23:50 UTC, richford commented
I'm also wondering about the visual encoding used here. Just my two cents here but I'd rather keep the colors of the circles consistent and shade the "background" of the table cell or something like that.

2024-02-07 00:22 UTC, Emily-ejag commented
Created a function to print the flags, since it was too much code :) , waiting for filtering to get fixed

2024-02-07 02:33 UTC, richford requested changes

2024-02-08 18:15 UTC, Emily-ejag commented
> This is looking great! @Emily-ejag could you please resolve the merge conflict? After that I think we are good to go!

Thank you!, Will do, I also want to add the text Carrie gives me first :)

2024-02-09 18:21 UTC, richford requested changes
@Emily-ejag, I requested some very minor adjustments. But then I think we are good to merge. Could you do `npm run format` also before pushing up the changes? Thanks for all of your hard work on this!

2024-02-09 18:21 UTC, richford commented on src/components/RoarDataTable.vue
> +          return flag;
```suggestion
          return _lowerCase(flag);
```

2024-02-09 18:21 UTC, richford commented on src/components/RoarDataTable.vue
> +// import _lowerCase from 'lodash/lowerCase';
Maybe we can keep this in here to handle the fallback case in the switch statement below
```suggestion
import _lowerCase from 'lodash/lowerCase';
```

2024-02-09 18:21 UTC, richford commented on src/components/RoarDataTable.vue
> +    // return '\n' + 'Reliability: ' + Object.keys(flags).map(_lowerCase).join(', ') + '\n';
```suggestion
```

2024-02-09 19:05 UTC, richford approved these changes

2024-02-09 19:06 UTC, merged