Allow Email login
yeatmanlab/roar-dashboard pull request #412
Opened 2024-03-08 18:48 UTC by kellyel

This PR adds the ability to log in using a password for email users.

2024-03-08 19:13 UTC, richford requested changes
Code review and testing of the PR preview link look good! Could I ask you to add or modify copies tests as well? I realize that the cypress test user will not be able to log in with email link. But maybe we could just write a test that toggles the password box and verifies that it is enabled/disabled.

2024-03-08 19:54 UTC, lucasxsong reviewed
This looks really good! I was testing on staging and noticed that this error prevented me from authing with email, but pulling down the changes and running the login flow on localhost worked. 

<img width="539" alt="image" src="https://github.com/yeatmanlab/roar-dashboard/assets/20426569/6507117f-b109-4f48-9da5-9d43f19294af">

I had a small design suggestion: would it be possible to style the disabled password input box to look more like the disabled example in the Primevue docs? The current disabled input box works well in dissuading users from trying to enter a password, but I feel that the visual hinting provided by the darkened input background might help users in quickly identifying what mode they are in (email/pw or email/link). What do you think? 

<img width="793" alt="image" src="https://github.com/yeatmanlab/roar-dashboard/assets/20426569/99ec529b-28af-420e-af4e-39d3bec71492">

2024-03-08 21:59 UTC, kellyel commented
Thanks for the review, Lucas.
Yes, I noticed that too. However that seems to be the case on all staging links right now. It seems firebase does not recognize the staging links as a valid uri. I just don't think that's been set up yet. It might be possible given that we use the firebase hosting github action to generate these. 

Yes, I agree with you. I can darken that background right now.

2024-03-11 18:08 UTC, richford approved these changes

2024-03-11 18:09 UTC, merged