WIP: Add Administration Search
yeatmanlab/roar-dashboard pull request #497
Opened 2024-04-09 17:58 UTC by lucasxsong

Removing paginated queries from administration page

2024-04-09 21:56 UTC, richford requested changes
@lucasxsong I love it! I made two comments that imply some requested changes:
- Can we avoid writing a new `administrationFetcher` function by passing in `page = 0` and `pageLimit = Number.MAX_SAFE_INTEGER` to the existing `administrationPageFetcher`?
- Can we use [Primevue's autocomplete component](https://primevue.org/autocomplete/) to suggest things as the user types?

2024-04-09 21:56 UTC, richford commented on src/helpers/query/administrations.js
> +};
Could we achieve the same thing by setting `page = 0` and `pageLimit = Number.MAX_SAFE_INTEGER` in the old `administrationPageFetcher`.

2024-04-09 21:56 UTC, richford commented on src/pages/HomeAdministrator.vue
> +                  >
Could we use Primevue's autocomplete component (https://primevue.org/autocomplete/) to suggest things as the user types?

2024-04-09 21:57 UTC, richford commented
Additionally, could you add a Cypress test for searching by name?

2024-04-10 00:16 UTC, richford approved these changes
LGTM. Approved!. Let's wait for Cypress tests to pass and get a second approval from either @Emily-ejag or @ksmontville.

2024-04-10 00:27 UTC, Emily-ejag approved these changes

2024-04-10 03:06 UTC, Emily-ejag requested changes
It is not working for PartnerAdmins therefore the tests are failing

2024-04-10 09:01 UTC, richford requested changes
I was thinking about this a bit more and I'd like to request an additional refactor. Currently, with `onSortChange` we initiate a new query. However, I think we should remove the `orderBy` from the query key so that we don't invalidate the query by sorting. After all, we already have all of the administration data locally. So I think we should just sort locally without running another query.

- Can you change the `onSortChange` function to edit `filteredAdministrations` in place?
- Sorting and searching can also interact. When a user sorts and then searches, we should return the results in their previously requested sort order. Similarly, when a user searches, then sorts, we should only sort the administrations returned by the search pattern.
- Lastly, once @Emily-ejag merges #498, then partner admins will see the public facing name stored in the `publicName` field. Given that the Cypress tests are failing here, I think it might be best to merge her PR first. Can you work with @Emily-ejag to edit `onSortChange` to sort by `publicName` if the user is a partner admin and by `name` if the user is a super admin?
- Similarly, can you search by `publicName` if the user is a partner admin and `name` if the user is a super admin?
- In the two cases above, if an administration doesn't have the `publicName` field, it should fall back on the `name` field.

2024-04-10 18:14 UTC, ksmontville requested changes

2024-04-10 18:14 UTC, ksmontville commented on cypress/e2e/super-admin/searchAdministrations.spec.cy.js
> +
```suggestion
const timeout = Cypress.env('timeout')
```

2024-04-10 18:14 UTC, ksmontville commented on cypress/e2e/super-admin/searchAdministrations.spec.cy.js
> +      cy.get('div').contains('Dates');
```suggestion

```

2024-04-10 21:52 UTC, richford approved these changes

2024-04-10 21:55 UTC, Emily-ejag approved these changes

2024-04-10 22:17 UTC, ksmontville approved these changes

2024-04-10 22:18 UTC, merged