LHT-273, LHT-274: Disabling sentry and consent form for levante instance
yeatmanlab/roar-dashboard pull request #567
Opened 2024-05-14 11:59 UTC by asengupta3

2024-05-14 16:39 UTC, Zio-4 commented
Not sure why but the 'Report an issue' button still shows on production. @asengupta3 any ideas why?

2024-05-14 22:27 UTC, Zio-4 requested changes
Comment I added earlier.

2024-05-15 12:47 UTC, asengupta3 commented
> Comment I added earlier.

@Zio-4 the staging preview is of a ROAR instance, isn't the levante instance a separate one?

2024-05-15 18:16 UTC, Zio-4 approved these changes

2024-05-15 18:17 UTC, merged