WIP: reliability flags for spanish apps
yeatmanlab/roar-dashboard pull request #605
Opened 2024-05-23 21:39 UTC by Emily-ejag

on scoreReport gray-out unreliable results for spanish apps

2024-05-28 23:09 UTC, richford requested changes

2024-05-28 23:24 UTC, Emily-ejag commented on src/components/reports/TableScoreTag.vue
>      // Join the returned flags with a newline character, then add two newlines for spacing
Sure

2024-05-29 00:19 UTC, Emily-ejag commented on src/pages/ScoreReport.vue
> -          currRowScores[taskId].tagColor = supportLevelColors.Assessed;
No, now that is relevant on line 698

2024-05-29 20:59 UTC, richford approved these changes

2024-05-29 22:41 UTC, ksmontville approved these changes

2024-05-29 22:53 UTC, merged