Game route path changes + vocab translations
yeatmanlab/roar-dashboard pull request #615
Opened 2024-05-28 21:38 UTC by Zio-4

These changes were required so that the LEVANTE version of Vocab would launch correctly. The two tasks have the same Id so it would default to the ROAR vocab task component.

2024-05-28 22:14 UTC, richford requested changes

2024-05-28 22:14 UTC, richford commented on src/translations/es/es-componentTranslations.json
Are you missing the corresponding changes in the /src/translations/es/co/es-co-componentTranslations.json file?

2024-05-28 23:49 UTC, Zio-4 commented on src/translations/es/es-componentTranslations.json
No, these are general Spanish translations. Not Colombia specific.

2024-05-29 01:25 UTC, Emily-ejag requested changes

2024-05-29 01:25 UTC, Emily-ejag commented on src/router/index.js
maybe this will affect the current administrations, I created one with trog and it is working fine on production, but on the pr link it is not found: 
<img width="1329" alt="image" src="https://github.com/yeatmanlab/roar-dashboard/assets/62304493/184434a2-ce8d-41e8-b939-0397f0196c25">

2024-05-29 01:25 UTC, Emily-ejag commented on src/router/index.js
Unless I manually add /core-tasks: 
<img width="1267" alt="image" src="https://github.com/yeatmanlab/roar-dashboard/assets/62304493/deb4a67b-7bf8-4d9d-85c4-6e3de3426016">

2024-05-29 17:35 UTC, Emily-ejag commented on src/router/index.js
> +    path: '/game/core-tasks/:taskId',
This one:
```suggestion
    path: '/game/core-tasks/:taskId',
```

2024-05-29 19:21 UTC, Zio-4 commented on src/router/index.js
Fixed. This won't break current administrations since it's just a routing change.

2024-05-29 20:50 UTC, Emily-ejag approved these changes

2024-05-29 23:17 UTC, closed without merging