add offline settings page
yeatmanlab/roar-dashboard pull request #723
Opened 2024-07-24 05:46 UTC by lucasxsong

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-07-29 22:03 UTC, ksmontville requested changes
I only tested briefly, but this is looking really great.

I am not sure that the delete buttons are properly removing tasks from my offline queue.

Also, one important thing that I think we should add is to re-fetch the data after the user saves their settings. Currently the user has to manually refresh the page after clicking "Save settings" in order to see their changes.

I suggest that clicking the "Save Settings" button triggers a re-fetch using tanstackquery.  I implemented something like this in Manage Tasks/Variants, which re-fetches the data after editing and submitting it to Firestore, after the toast pops up.

You declare a queryClient and then use the invalidateQueries method to manually trigger a re-fetch. Modify to suit your specifi queries.

`import { useQuery, useQueryClient } from '@tanstack/vue-query';
const queryClient = useQueryClient();`

  try {
    await authStore.roarfirekit.updateTaskOrVariant(updateData);
    toast.add({ severity: 'success', summary: 'Hoorah!', detail: 'Variant successfully updated.', life: 3000 });

    // Reset the form and re-fetch the data
    resetUpdateVariantForm();
    await queryClient.invalidateQueries(['tasks', registeredTasksOnly]);
    await queryClient.invalidateQueries(['variants', 'all']);
  } catch (error) {
    console.error(error);
  }
};
`

2024-07-30 21:09 UTC, kellyel approved these changes

2024-08-05 18:30 UTC, ksmontville requested changes
Looking good!

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +            v-for="name in selectedOfflineAdministrations"
```suggestion
            v-for="name in selectedOfflineAdministrations" :key="name"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +        <PvToggleButton v-model="offlineEnabled" onLabel="On" offLabel="Off" class="p-2 rounded" />
```suggestion
        <PvToggleButton v-model="offlineEnabled" on-label="On" off-label="Off" class="p-2 rounded" />
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +                :onClick="() => removeOfflineTask(name)"
```suggestion
                @click="() => removeOfflineTask(name)"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +            :onClick="addOfflineAdministration"
```suggestion
            @click="addOfflineAdministration"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +                :onClick="() => removeOfflineAdministration(name)"
```suggestion
                @click="() => removeOfflineAdministration(name)"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +          :onClick="saveOfflineSettings"
```suggestion
          @click="saveOfflineSettings"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +          :onClick="saveOfflineSettings"
```suggestion
          @click="saveOfflineSettings"
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +import { useQuery, QueryClient } from '@tanstack/vue-query';
```suggestion
import { useQuery, useQueryClient } from '@tanstack/vue-query';
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +const queryClient = new QueryClient();
```suggestion
const queryClient = useQueryClient()
```

2024-08-05 18:30 UTC, ksmontville commented on src/components/views/OfflineSettings.vue
> +  queryClient.invalidateQueries(['userData', uid]);
```suggestion
await queryClient.invalidateQueries(['userData', uid]);
```
Either `await` this or move it into the .then() block above (don't think it matters which one).

2024-08-05 19:39 UTC, ksmontville approved these changes

2024-08-05 20:56 UTC, merged