Enh/isr add letter
yeatmanlab/roar-dashboard pull request #744
Opened 2024-08-14 21:57 UTC by kellyel

## Proposed changes
This PR adds letter to the individual score report page. It is listed as a raw score task.

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [x] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [x] Linting checks pass with my changes.
- [x] Any existing unit tests pass with my changes.
- [x] Any existing end-to-end tests pass with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-08-15 16:27 UTC, kellyel commented on src/components/reports/IndividualScoreReportTask.vue
> +    console.log('rawScoreKey', rawScoreKey);
Done, thanks for catching those!

2024-08-15 16:34 UTC, Emily-ejag approved these changes

2024-08-15 16:37 UTC, kellyel commented
Emily and I have discussed that issue through slack, we have determined that this issue is unrelated this PR. Thanks Emily for bringing it up, it is definitely an issue that needs attention!

2024-08-15 21:26 UTC, richford requested changes

2024-08-15 21:26 UTC, richford commented on src/components/reports/IndividualScoreReportTask.vue
> +    //   !taskId.includes('vocab') && !taskId.includes('es') ? _get(compositeScores, rawScoreKey) : compositeScores;
```suggestion

```

2024-08-16 18:03 UTC, richford approved these changes

2024-08-16 18:03 UTC, merged