fix/Edit Administrations
yeatmanlab/roar-dashboard pull request #754
Opened 2024-08-21 19:54 UTC by ksmontville

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-08-21 21:54 UTC, Emily-ejag commented on src/components/CreateAdministration.vue
>      console.log('found', found);
```suggestion
 
```

2024-08-21 21:54 UTC, Emily-ejag commented on src/components/CreateAdministration.vue
>    if (found) {
```suggestion

```

2024-08-21 21:55 UTC, Emily-ejag commented on src/components/CreateAdministration.vue
>    }
```suggestion

```

2024-08-21 21:55 UTC, Emily-ejag commented on src/components/CreateAdministration.vue
>    console.log(`attempting to find variant of ${variants[0].task.id}`);
```suggestion

```

2024-08-21 21:56 UTC, Emily-ejag commented
This is working so good! thanks Kyle. there is just a tiny thing that is not working and is when selecting `This administration does not require consent or assent forms` save and then try to edit, that particular selection is not showing, the rest is working fine.

2024-08-21 21:59 UTC, Emily-ejag requested changes
Also, sometimes on the first time I want to edit it does not show the `Selected organizations` and sometimes the names and dates. The warnings I see are the ones in the picture. But once I refresh It looks fine, and not warnings 
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/b40a199c-cdd1-4ba2-a7dd-986d20e81034">

2024-08-22 18:49 UTC, ksmontville commented
> This is working so good! thanks Kyle. there is just a tiny thing that is not working and is when selecting `This administration does not require consent or assent forms` save and then try to edit, that particular selection is not showing, the rest is working fine.

I fixed the checkbox issue and blank fields issue, do you mind taking another look?

2024-08-22 19:11 UTC, Emily-ejag commented
It is awesome!! I think the only mark as test is not being pulled. But the rest is smooth like butter :) 
<img width="297" alt="image" src="https://github.com/user-attachments/assets/db2af908-0ee5-4861-b426-f86249cdac65">

2024-08-22 19:16 UTC, Emily-ejag approved these changes

2024-08-23 22:48 UTC, kellyel approved these changes

2024-08-23 23:28 UTC, richford approved these changes

2024-08-24 00:03 UTC, merged