Restore default sort
yeatmanlab/roar-dashboard pull request #774
Opened 2024-09-03 21:37 UTC by kellyel

## Proposed changes
Update the format of the default sort to make it functional on score and progress reports.

## Types of changes

What types of changes does this pull request introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [x] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [x] Linting checks pass with my changes.
- [x] Any existing unit tests pass with my changes.
- [x] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [x] I have added JSDoc comments as appropriate.
- [x] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [x] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [x] I have linked relevant issues (if any)

## Justification of missing checklist items

## Testing Steps
- Navigate to score report
- After table loads, there should already be a sort applied - school (1), grade (2), and last name (3)
- Navigate to a progress report
- Should see the same default sort without any manual intervention.

## Further comments
Interface defined here: https://v3.primevue.org/datatable/#pre_sort

2024-09-03 23:28 UTC, lucasxsong approved these changes

2024-09-04 16:08 UTC, Emily-ejag requested changes
The only issue I see is that K grade is being placed as bigger, because it is a letter --> Is there a way to associate K with 0?

2024-09-04 17:11 UTC, kellyel commented
> The only issue I see is that K grade is being placed as bigger, because it is a letter --> Is there a way to associate K with 0?

This is an existing issue we know we want to address. It may be outside of the scope of this PR, as PrimeVue doesn't support custom sort functions for the table as far as I can find, which leaves hacking a solution. I've just tried one solution, and it seems to be ineffective. This leads me to believe that this solution might need more thought with a separate PR.

2024-09-04 17:22 UTC, Emily-ejag commented
> > The only issue I see is that K grade is being placed as bigger, because it is a letter --> Is there a way to associate K with 0?
> 
> This is an existing issue we know we want to address. It may be outside of the scope of this PR, as PrimeVue doesn't support custom sort functions for the table as far as I can find, which leaves hacking a solution. I've just tried one solution, and it seems to be ineffective. This leads me to believe that this solution might need more thought with a separate PR.

Thanks for clarifying @kellyel :)

2024-09-04 17:22 UTC, Emily-ejag approved these changes

2024-09-04 21:09 UTC, merged