Replace `uid` with `roarUid` on ClassLink landing page
yeatmanlab/roar-dashboard pull request #836
Opened 2024-09-27 19:17 UTC by maximilianoertel

## Proposed changes
As discussed with @richford, this PR updates the user type check on the ClassLink landing page to use the `roarUid` instead of `uid`. As this function is identical on both this and the Clever page, a separate PR will be opened to refactor the function into a reusable helper.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-09-27 19:25 UTC, richford requested changes

2024-09-27 19:25 UTC, richford commented on src/pages/ClassLinkLanding.vue
> +  `Arrived at ClassLinkLanding.vue with uid: ${roarUid.value} and authFromClever: ${authFromClassLink.value} `,
```suggestion
  `Arrived at ClassLinkLanding.vue with uid: ${roarUid.value} and authFromClassLink: ${authFromClassLink.value} `,
```

2024-09-30 20:14 UTC, richford approved these changes

2024-09-30 20:15 UTC, kellyel approved these changes

2024-09-30 20:18 UTC, merged