Replace roam-fluency with roam-apps
yeatmanlab/roar-dashboard pull request #885
Opened 2024-10-14 22:40 UTC by ksmontville

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-10-14 22:59 UTC, KruttikaBhat approved these changes

2024-10-15 15:31 UTC, richford requested changes
The code changes all look good to me. However, @ksmontville, do you understand why the participant tests are failing?

2024-10-15 21:05 UTC, Emily-ejag submitted a review, later dismissed

2024-10-15 21:08 UTC, Emily-ejag approved these changes

2024-10-15 23:14 UTC, Emily-ejag approved these changes

2024-10-16 17:41 UTC, kellyel approved these changes

2024-10-16 17:42 UTC, merged