simplify assent/consent title
yeatmanlab/roar-dashboard pull request #932
Opened 2024-11-04 21:26 UTC by lucasxsong

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-11-05 18:40 UTC, Emily-ejag approved these changes
LGTM

2024-11-05 18:40 UTC, Emily-ejag commented
You will need to change the cypress test, to only look for Consent :)

2024-11-05 21:24 UTC, Emily-ejag submitted a review, later dismissed

2024-11-07 17:50 UTC, richford requested changes

2024-11-07 17:50 UTC, richford commented on src/components/ConsentModal.vue
> +  const header = props.consentType.includes('consent') ? `Consent` : `Assent`;
It seems like you got rid of the translations in this refactor. Was that intentional? If so, can you justify the removal?

2024-11-11 18:34 UTC, richford requested changes

2024-11-11 18:34 UTC, richford commented on cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
> +    cy.get('.p-dialog-title', { timeout: timeout }).contains('Consent').should('be.visible');
```suggestion
    cy.get('.p-dialog-title', { timeout: timeout }).contains(i18n.t('consentModalo.consentTitle')).should('be.visible');
```

2024-11-11 18:37 UTC, lucasxsong commented on cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
> +    cy.get('.p-dialog-title', { timeout: timeout }).contains('Consent').should('be.visible');
Thanks for catching this!

2024-11-11 18:39 UTC, richford submitted a review, later dismissed

2024-11-11 18:42 UTC, Emily-ejag submitted a review, later dismissed

2024-11-11 19:29 UTC, Emily-ejag approved these changes

2024-11-11 19:31 UTC, merged